#!/bin/bash

TS3_VERSION_LATEST=$(wget -qO- $TS3_VERSION_ENDPOINT)

if [ -f ./.updateme ]; then
  exit 0
fi

# Thanks to Paused until further notice.
# https://stackoverflow.com/a/4025065
vercomp () {
  if [[ $1 == $2 ]]
  then
      return 0
  fi
  local IFS=.
  local i ver1=($1) ver2=($2)
  # fill empty fields in ver1 with zeros
  for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
  do
      ver1[i]=0
  done
  for ((i=0; i<${#ver1[@]}; i++))
  do
      if [[ -z ${ver2[i]} ]]
      then
          # fill empty fields in ver2 with zeros
          ver2[i]=0
      fi
      if ((10#${ver1[i]} > 10#${ver2[i]}))
      then
          return 1
      fi
      if ((10#${ver1[i]} < 10#${ver2[i]}))
      then
          return 2
      fi
  done
  return 0
}

if [ vercomp $TS3_VERSION_LATEST == 1 ]; then
  touch ./.updateme
fi